events {
    worker_connections 1024;
}

http {
    # ── ZONES DE RATE LIMITING ──────────────────────────────────────────────
    # Zone 1 : Trafic normal pour le Dashboard (10 requêtes par seconde)
    limit_req_zone $binary_remote_addr zone=ui_limit:10m rate=10r/s;
    
    # Zone 2 : Trafic API strict pour bloquer le Brute Force (2 requêtes max/sec)
    limit_req_zone $binary_remote_addr zone=login_limit:10m rate=2r/s;

    server {
        listen 80;

        # 1. LA LISTE BLANCHE PROMETHEUS (Exception de sécurité)
        # On n'applique simplement aucune zone limit_req ici.
        location /metrics {
            proxy_pass http://auth-service:5001/metrics;
        }

        # 2. LE BOUCLIER BRUTE FORCE (API Auth)
        location /api/auth/ {
            limit_req zone=login_limit burst=15 nodelay;
            limit_req_status 429;
            proxy_pass http://auth-service:5001/api/auth/;
        }

        # 3. LE ROUTAGE STANDARD (Frontend)
        location / {
            limit_req zone=ui_limit burst=20 nodelay;
            proxy_pass http://frontend:8080/;
        }
    }
}